In [121]:
import pandas as pd
import re
#!pip install IMDbPY
import imdb

In [122]:
imdb_link =imdb.IMDb()

In [170]:
import os

def find_repo_root(start_path):
    """
    useful general function for finding the (first, closest) repo root so github file paths work the same on different machines 
    """
    current_path = os.path.abspath(start_path)
    
    while True:
        # Check for the existence of the .git directory or other indicators
        if os.path.isdir(os.path.join(current_path, '.git')) or \
           os.path.isfile(os.path.join(current_path, 'README.md')):
            return current_path
        
        parent_path = os.path.dirname(current_path)
        
        # Stop if we reach the root directory
        if parent_path == current_path:
            break
        
        current_path = parent_path

    return None  # Return None if not found

root = find_repo_root(os.getcwd())
print(root)

c:\Users\fitsl\Documents\Programming\UVM Programming Classes\PoCS\pocs_project

In [124]:
# try to download one...

path = f'{root}/Data/international-movies-json/international-movies-json/0a0dd971-0c66-4fd2-8391-d5c460d6d675.json'

df = pd.read_json(path)
print(df.columns)
print(df.shape)

Index(['ImdbId', '_id', 'name', 'poster_url', 'year', 'certificate', 'runtime',
       'genre', 'ratingValue', 'summary_text', 'ratingCount', 'director',
       'cast'],
      dtype='object')
(250, 13)

In [125]:
# looks good so download a second...

df_2 = f"{root}/Data/international-movies-json/international-movies-json/0a5dba0c-d6e3-4b79-a699-ccefa442b86d.json"
df_2 = pd.read_json(df_2)
print(df_2.columns)
print(df_2.shape)
df_2.head()

Index(['ImdbId', '_id', 'name', 'poster_url', 'year', 'certificate', 'runtime',
       'genre', 'ratingValue', 'summary_text', 'ratingCount', 'director',
       'cast'],
      dtype='object')
(250, 13)

,ImdbId,_id,name,poster_url,year,certificate,runtime,genre,ratingValue,summary_text,ratingCount,director,cast
0,tt10521318,tt10521318,Music for Getting Married,https://m.media-amazon.com/images/S/sash/NapCx...,2018,,,[],,Add a Plot,,NaN,NaN
1,tt10521312,tt10521312,Mi Hijo,https://m.media-amazon.com/images/S/sash/NapCx...,2018,,,[],,Add a Plot,,NaN,NaN
2,tt10521310,tt10521310,Un Tal Eduardo,https://m.media-amazon.com/images/M/MV5BNWE0OW...,2018,,,[],,Add a Plot,,"{'name': 'Aldo Garay', 'name_id': 'nm1212968'}",[]
3,tt10521308,tt10521308,Jonas Kaufmann: My Italy,https://m.media-amazon.com/images/M/MV5BOWMwND...,2017,,85 min,[Music],,Add a Plot,,NaN,NaN
4,tt10521306,tt10521306,Colmena,https://m.media-amazon.com/images/S/sash/NapCx...,2018,,,[],,Add a Plot,,NaN,NaN

In [126]:
#see if they combine painlessly

df_combo = pd.concat([df, df_2], ignore_index=True)
print(df_combo.columns)
print(df_combo.shape)

Index(['ImdbId', '_id', 'name', 'poster_url', 'year', 'certificate', 'runtime',
       'genre', 'ratingValue', 'summary_text', 'ratingCount', 'director',
       'cast'],
      dtype='object')
(500, 13)

In [127]:
## see how many folders we have
print(len([f for f in os.listdir(f'{root}/Data/international-movies-json/international-movies-json')]))

2535

In [128]:
# #cool. Now we can get programmatic about it and combine them all... 


# # once you run this, comment it out to save space

# i=0
# df_combo = pd.DataFrame()
# for filename in os.listdir(f"{root}/Data/international-movies-json/international-movies-json"):
#     i += 1
#     print(f"processing {i} :  {filename}")
#     df_combo = pd.concat(
#         [
#             df_combo, pd.read_json(f"{root}/Data/international-movies-json/international-movies-json/{filename}")
#             ], 
#          ignore_index=True)

In [129]:
print(df_combo.shape)
print(df_combo.columns)

(500, 13)
Index(['ImdbId', '_id', 'name', 'poster_url', 'year', 'certificate', 'runtime',
       'genre', 'ratingValue', 'summary_text', 'ratingCount', 'director',
       'cast'],
      dtype='object')

In [130]:
## this dataframe at least initially looks pretty good so we save it as a csv for later. 
# Note that we add this to gitignore because it's too large to push back and forth. so you'll have to make it yourself by running all this code


# df_combo.to_csv(f"{root}/Data/IMBD_Dataframe.csv", index=False )

In [131]:
imdb_df = pd.read_csv(f"{root}/Data/IMBD_Dataframe.csv")
imdb_df.columns

Index(['ImdbId', '_id', 'name', 'poster_url', 'year', 'certificate', 'runtime',
       'genre', 'ratingValue', 'summary_text', 'ratingCount', 'director',
       'cast'],
      dtype='object')

In [132]:
imdb_df[imdb_df['name'].str.contains("Better Off").astype("bool")]

,ImdbId,_id,name,poster_url,year,certificate,runtime,genre,ratingValue,summary_text,ratingCount,director,cast
8050,tt0158963,tt0158963,A Site Better Off,https://m.media-amazon.com/images/S/sash/NapCx...,1989 TV Movie,NaN,NaN,['Documentary'],NaN,Add a Plot,NaN,"{'name': 'Martin Denning', 'name_id': 'nm02193...",[]
61038,tt4799172,tt4799172,Better Off,https://m.media-amazon.com/images/M/MV5BNzhjN2...,2015 TV Movie,NaN,22 min,['Comedy'],NaN,"After 20 years of marriage, Blanton and Celest...",NaN,"{'name': 'Peter Hyoguchi', 'name_id': 'nm04052...","[{'name': 'Tiffany Abney', 'name_id': 'nm45892..."
185193,tt11575508,tt11575508,Better Off Dead,https://m.media-amazon.com/images/S/sash/NapCx...,2021,NaN,50 min,['Horror'],NaN,Add a Plot,NaN,"{'name': 'Lakota Hawkins', 'name_id': 'nm10940...","[{'name': 'Lakota Hawkins', 'name_id': 'nm1094..."
325100,tt2081374,tt2081374,Better Off Single,https://m.media-amazon.com/images/M/MV5BMjMwNT...,2016,Not Rated,85 min,['Comedy'],4.3,"""Better Off Single"" is the NYC dating comedy t...",728,"{'name': 'Benjamin Cox', 'name_id': 'nm1639704'}","[{'name': 'Aaron Tveit', 'name_id': 'nm3117836..."
458687,tt5774076,tt5774076,NaN,https://m.media-amazon.com/images/M/MV5BNDExZT...,2015,NaN,NaN,"['Action', ' Drama', ' Mystery']",NaN,Two boys throw a party while their parents are...,NaN,"{'name': 'G.M. Whiting', 'name_id': 'nm6825011'}","[{'name': 'Israel Adam', 'name_id': 'nm6833864..."
507092,tt7248518,tt7248518,Better Off Zed,https://m.media-amazon.com/images/M/MV5BYmE5Yj...,2018,TV-MA,88 min,"['Comedy', ' Drama', ' Horror']",4.4,What if the apocalypse came... and you were ha...,215,"{'name': 'Travis Stevens', 'name_id': 'nm21176...","[{'name': 'Christine Woods', 'name_id': 'nm214..."
520102,tt0088794,tt0088794,Better Off Dead...,https://m.media-amazon.com/images/M/MV5BMzRmMj...,1985,PG,97 min,"['Comedy', ' Romance']",7.1,After his girlfriend ditches him for a boorish...,"41,870","{'name': 'Savage Steve Holland', 'name_id': 'n...","[{'name': 'John Cusack', 'name_id': 'nm0000131..."
576582,tt0106398,tt0106398,Better Off Dead,https://m.media-amazon.com/images/M/MV5BMDZkOT...,1993 TV Movie,NaN,120 min,['Drama'],6.5,A lawyer fights a losing battle against the co...,95,"{'name': 'Neema Barnette', 'name_id': 'nm00560...","[{'name': 'Mare Winningham', 'name_id': 'nm000..."

In [133]:
df_tropes = pd.read_csv(f"{root}/Data/movies-vs-tropes.csv", sep=';')
df_tropes.shape

(14560, 2)

In [134]:
imdb_df.shape

(633719, 13)

In [135]:
df_tropes['Movie'] = df_tropes['Movie'].map(lambda text :  re.sub(r'(?<!^)(?=[A-Z])', ' ', text)) ## puts a space before any capital letter 
df_tropes['Movie'] = df_tropes['Movie'].map(lambda text : re.sub(r'(?<!\d)(19[0-9]{2}|20[0-1][0-9]|202[0-4])(?!\d)', r' \1', text)) #puts a space between any four year sequence (used to tell apart sequels)
df_tropes.head(30)

,Movie,Tropes
0,Puerta De Hierro,"ArgentineMedia,BlackMagic,ChekhovsGun,Chekhov..."
1,Better Off Dead...,"AbhorrentAdmirer,AcceptableTargets,ActorAllus..."
2,A War,"CallBack,CigaretteOfAnxiety,CouldSayItBut,Dan..."
3,Team America World Police,"ADegreeInUseless,AHeroToHisHometown,AbstractS..."
4,The Hills Have Eyes 2006,"AdaptationDistillation,AdaptationExpansion,Ad..."
5,The Face Of Fu Manchu,"ActuallyADoombot,AffablyEvil,ArchEnemy,Awesom..."
6,The Trip To Bountiful,"BittersweetEnding,EarnYourHappyEnding,ElderAb..."
7,Frantz,"AllLoveIsUnrequited,AnArmAndALeg,DaydreamSurp..."
8,Bad Company 2002,"BackUpTwin,BackupTwin,CoupDeGrace,EmergencyIm..."
9,The Last Stand,"ActionGirl,ArtisticLicenseCars,ArtisticLicens..."
10,Gosford Park,"AcceptableCulturalTargets,AllForNothing,Ambig..."
11,The Dawns Here Are Quiet,"AbsenceMakesTheHeartGoYonder,AllMyFriendsAreD..."
12,The Best Years Of Our Lives,"AbilityOverAppearance,AnArmAndALeg,ArtificIal..."
13,Biutiful,"AbusiveParents,AdultFear,AwardBait,Bitterswee..."
14,Inside Man,"AbsenceOfEvidence,AfricanAmericanMedia,Asshol..."
15,Clothes Of Deception,"AsYouKnow,BathtubScene,CatFight,ChekhovsGunma..."
16,The Time Machine 1978,"AdaptationExpansion,ArmsDealer,ArtisticLicens..."
17,The Immaculate Conception Of Little Dizzle,"BizarreAlienBiology,BookEnds,ChekhovsGun,Corr..."
18,Night On Earth,"AccidentalMisnaming,AdultFear,AnthologyFilm,A..."
19,On The Wrong Track,"BoomHeadshot,CallingTheOldManOut,ComingOfAge,..."
20,Out Of The Furnace,"AntiHero,BigBad,CorruptHick,DisproportionateR..."
21,The Purge,"AbortedArc,AdultFear,AdvertisingByAssociation..."
22,Night School,"AfricanAmericanMedia,BewareTheNiceOnes,BookDu..."
23,Mr Nanny,"AmusingInjuries,DoubleStandardViolenceChildOn..."
24,Nightwish,"AndYouWereThere,ChestBurster,Chestburster,Cre..."
25,Gods Not Dead2,"AffablyEvil,AlwaysChaoticEvil,AlwaysLawfulEvi..."
26,Reform School Girls,"AbusiveParents,BigEater,ButtBrand,CannedOrder..."
27,The Monster Of Phantom Lake,"AssholeVictim,BeatCop,BodyHorror,BotanicalAbo..."
28,Final Destination4,"AllThereInTheManual,AssholeVictim,BloodFromTh..."
29,Tart,"AnnoyingYoungerSibling,BathTubBonding,Bathtub..."

In [136]:
df_tropes['Movie'].isna().sum()

np.int64(0)

In [137]:
df_tropes[df_tropes['Movie'].str.match(r'.*\d{4}$')]

,Movie,Tropes
4,The Hills Have Eyes 2006,"AdaptationDistillation,AdaptationExpansion,Ad..."
8,Bad Company 2002,"BackUpTwin,BackupTwin,CoupDeGrace,EmergencyIm..."
16,The Time Machine 1978,"AdaptationExpansion,ArmsDealer,ArtisticLicens..."
30,Roma 1972,"AnachronicOrder,AsideGlance,AutoErotica,Blood..."
32,Venom 2018,"ADHD,AbledInTheAdaptation,AbortedArc,Acclaime..."
...,...,...
14525,The Magnificent Seven 2016,"AFistfulOfRehashes,AGoodWayToDie,AGoodWaytoDi..."
14526,The Master 1980,"ActionPrologue,BadassTeacher,BareFistedMonk,B..."
14549,Dracula 2000,"AdaptationalVillainy,AnnualTitle,ArtisticLice..."
14551,Berserk 1967,"AlphaBitch,BerserkButton,BloodlessCarnage,Bra..."
14554,Edmond 2019,"ARoundOfDrinksForTheHouse,AccidentalMisnaming..."

In [138]:
def strip_year(text):
    if pd.isna(text):
        print(text)
        return text # Return NaN and None if text is NaN
    
    match = pd.Series(text).str.extract(r'(\s(\d{4}))$')
    if not match.empty:
        return text.replace(str(match[0][0]), '').strip()
    return text


def get_year(text):
    if pd.isna(text):
        return None # Return NaN and None if text is NaN
    
    match = pd.Series(text).str.extract(r'(\s(\d{4}))$')
    if not match.empty:
        return match[1][0]
    return None

df_tropes['Movie_strip'] = df_tropes['Movie'].map(lambda x: strip_year(x))
df_tropes['year'] = df_tropes['Movie'].map(lambda x: get_year(x))

In [139]:
df_tropes

,Movie,Tropes,Movie_strip,year
0,Puerta De Hierro,"ArgentineMedia,BlackMagic,ChekhovsGun,Chekhov...",Puerta De Hierro,NaN
1,Better Off Dead...,"AbhorrentAdmirer,AcceptableTargets,ActorAllus...",Better Off Dead...,NaN
2,A War,"CallBack,CigaretteOfAnxiety,CouldSayItBut,Dan...",A War,NaN
3,Team America World Police,"ADegreeInUseless,AHeroToHisHometown,AbstractS...",Team America World Police,NaN
4,The Hills Have Eyes 2006,"AdaptationDistillation,AdaptationExpansion,Ad...",The Hills Have Eyes,2006
...,...,...,...,...
14555,Remember The Titans,"AfricanAmericanMedia,AmbiguouslyGay,ArmorPier...",Remember The Titans,NaN
14556,Deep Impact,"ActionFilmQuietDramaScene,AltarTheSpeed,Alumi...",Deep Impact,NaN
14557,Lost Horizon,"AcceptableReligiousTargets,AdaptationalJobCha...",Lost Horizon,NaN
14558,Kamen Rider The Next,"AdaptationalVillainy,AdaptedOut,AssKickingPos...",Kamen Rider The Next,NaN
14559,Princess Cyd,"ADateWithRosiePalms,ADateWithrosiePalms,Armor...",Princess Cyd,NaN

In [140]:
df_tropes['Movie'] = df_tropes['Movie_strip']
df_tropes = df_tropes.rename(columns=
                 {
                     ' Tropes' : "Tropes"
                 })
df_tropes['Movie'] = df_tropes['Movie'].map(lambda text :  re.sub(r'(?<!^)(?=[A-Z])', ' ', text))

In [141]:
# df_tropes['Movie'] =  df_tropes['Movie'].map(lambda x: re.sub(r'(\d)', r' \1', x, count=1))
# df_tropes['Movie'] = df_tropes['Movie'].map(lambda x : x.strip().lower())
# imdb_df['Movie'] = imdb_df['Movie'].map(lambda x : str(x)).map(lambda s: re.sub(r'[^\w\s]', '', s))
# imdb_df['Movie'] = imdb_df['Movie'].map(lambda x : x.strip().lower()).map(lambda s: re.sub(r'[^\w\s]', '', s))

In [142]:
imdb_link.search_movie("venom")

[<Movie id:16366836[http] title:_Venom: The Last Dance (2024)_>,
 <Movie id:1270797[http] title:_Venom (2018)_>,
 <Movie id:7097896[http] title:_Venom: Let There Be Carnage (2021)_>,
 <Movie id:0428251[http] title:_Venom (2005)_>,
 <Movie id:0084854[http] title:_Venom (1981)_>,
 <Movie id:6254596[http] title:_"Venom" (None)_>,
 <Movie id:0125764[http] title:_Venom (1966)_>,
 <Movie id:0067934[http] title:_The Legend of Spider Forest (1971)_>,
 <Movie id:1931601[http] title:_Venom (2011)_>,
 <Movie id:0417148[http] title:_Snakes on a Plane (2006)_>,
 <Movie id:7412114[http] title:_Red Venom Kills (2017)_>,
 <Movie id:5019312[http] title:_Venom (2015)_>,
 <Movie id:16911700[http] title:_Medusa's Venom (2023) (V)_>,
 <Movie id:14153900[http] title:_Venom Coast (2021)_>,
 <Movie id:1241018[http] title:_Silent Venom (2009) (V)_>,
 <Movie id:0416287[http] title:_Venom (2004)_>,
 <Movie id:3083812[http] title:_Venom: Truth in Journalism (2013)_>,
 <Movie id:10755644[http] title:_Lego Marvel Spider-Man: Vexed by Venom (2019) (TV)_>,
 <Movie id:0207801[http] title:_Venom and Eternity (1951)_>,
 <Movie id:13154232[http] title:_Spider-Man: The Venom Saga (2005) (V)_>]

In [164]:
imdb_link =imdb.IMDb()

def search_movie(link, title, year=None):
    if pd.isna(year):
        year = None
    else:
        year = str(year)
        # print(year)
    
    # Search for movies with the given title
    results = link.search_movie(title)

    if not results:  # Check if there are any results
        print("No results found for:", title)
        return None
    
    # Filter results by year
    if year:
        for movie in results:
            # print(movie)
            if movie.get('year') == year:
                return movie.movieID # Return the movie data if found
    return results[0].movieID

In [159]:
result = search_movie(imdb_link, 'venom')

In [160]:
df_tropes

,Movie,Tropes,Movie_strip,year
0,Puerta De Hierro,"ArgentineMedia,BlackMagic,ChekhovsGun,Chekhov...",Puerta De Hierro,NaN
1,Better Off Dead...,"AbhorrentAdmirer,AcceptableTargets,ActorAllus...",Better Off Dead...,NaN
2,A War,"CallBack,CigaretteOfAnxiety,CouldSayItBut,Dan...",A War,NaN
3,Team America World Police,"ADegreeInUseless,AHeroToHisHometown,AbstractS...",Team America World Police,NaN
4,The Hills Have Eyes,"AdaptationDistillation,AdaptationExpansion,Ad...",The Hills Have Eyes,2006
...,...,...,...,...
14555,Remember The Titans,"AfricanAmericanMedia,AmbiguouslyGay,ArmorPier...",Remember The Titans,NaN
14556,Deep Impact,"ActionFilmQuietDramaScene,AltarTheSpeed,Alumi...",Deep Impact,NaN
14557,Lost Horizon,"AcceptableReligiousTargets,AdaptationalJobCha...",Lost Horizon,NaN
14558,Kamen Rider The Next,"AdaptationalVillainy,AdaptedOut,AssKickingPos...",Kamen Rider The Next,NaN
14559,Princess Cyd,"ADateWithRosiePalms,ADateWithrosiePalms,Armor...",Princess Cyd,NaN

In [161]:
tropes_small = df_tropes[0:10].copy()
tropes_small.columns = tropes_small.columns.str.strip()
print(tropes_small['year'])

0     NaN
1     NaN
2     NaN
3     NaN
4    2006
5     NaN
6     NaN
7     NaN
8    2002
9     NaN
Name: year, dtype: object

In [147]:
tropes_small.dtypes

Movie          object
Tropes         object
Movie_strip    object
year           object
dtype: object

In [163]:
tropes_small['imdb_id'] = tropes_small.apply(lambda row: search_movie(
    imdb_link, row['Movie_strip'], row['year']) , 
     axis=1)

tropes_small

2006
2002

,Movie,Tropes,Movie_strip,year,imdb_id
0,Puerta De Hierro,"ArgentineMedia,BlackMagic,ChekhovsGun,Chekhov...",Puerta De Hierro,NaN,2512204
1,Better Off Dead...,"AbhorrentAdmirer,AcceptableTargets,ActorAllus...",Better Off Dead...,NaN,0088794
2,A War,"CallBack,CigaretteOfAnxiety,CouldSayItBut,Dan...",A War,NaN,17279496
3,Team America World Police,"ADegreeInUseless,AHeroToHisHometown,AbstractS...",Team America World Police,NaN,0372588
4,The Hills Have Eyes,"AdaptationDistillation,AdaptationExpansion,Ad...",The Hills Have Eyes,2006,0454841
5,The Face Of Fu Manchu,"ActuallyADoombot,AffablyEvil,ArchEnemy,Awesom...",The Face Of Fu Manchu,NaN,0059162
6,The Trip To Bountiful,"BittersweetEnding,EarnYourHappyEnding,ElderAb...",The Trip To Bountiful,NaN,0090203
7,Frantz,"AllLoveIsUnrequited,AnArmAndALeg,DaydreamSurp...",Frantz,NaN,5029608
8,Bad Company,"BackUpTwin,BackupTwin,CoupDeGrace,EmergencyIm...",Bad Company,2002,0280486
9,The Last Stand,"ActionGirl,ArtisticLicenseCars,ArtisticLicens...",The Last Stand,NaN,1549920

In [169]:
print(root)

c:\Users\fitsl\Documents\Programming\UVM Programming Classes\PoCS\pocs_project

In [175]:

df_tropes.columns  = df_tropes.columns.str.strip()
## see most recent printout to know where to start 
chunk_size = 100
for start in range(12200  , len(df_tropes), chunk_size):
    end = start + chunk_size
    print(f"starting {start} to {end}")
    chunk = df_tropes.iloc[start:end].copy()

    # Apply the search_movie function to the chunk
    chunk['imdb_'] = chunk.apply(
        lambda row: search_movie(imdb_link, row['Movie_strip'], row['year']),
        axis=1
    )
    
    # Save the chunk to a CSV or append to an existing one
    chunk.to_csv(f'{root}/Data/tropes_with_imfb.csv', mode='a', header=not pd.io.common.file_exists('results.csv'), index=False)
    print(f"completed {start} to {end} \n\n")

starting 12200 to 12300
completed 12200 to 12300


starting 12300 to 12400
completed 12300 to 12400


starting 12400 to 12500
completed 12400 to 12500


starting 12500 to 12600
No results found for: Noob La Quete Legendaire
completed 12500 to 12600


starting 12600 to 12700
completed 12600 to 12700


starting 12700 to 12800
completed 12700 to 12800


starting 12800 to 12900
completed 12800 to 12900


starting 12900 to 13000
completed 12900 to 13000


starting 13000 to 13100
completed 13000 to 13100


starting 13100 to 13200
completed 13100 to 13200


starting 13200 to 13300
No results found for: Himitsu Sentai Goranger Fire Mountains Final Explosion
completed 13200 to 13300


starting 13300 to 13400
completed 13300 to 13400


starting 13400 to 13500
completed 13400 to 13500


starting 13500 to 13600
completed 13500 to 13600


starting 13600 to 13700
completed 13600 to 13700


starting 13700 to 13800
completed 13700 to 13800


starting 13800 to 13900
completed 13800 to 13900


starting 13900 to 14000
completed 13900 to 14000


starting 14000 to 14100
completed 14000 to 14100


starting 14100 to 14200
completed 14100 to 14200


starting 14200 to 14300
completed 14200 to 14300


starting 14300 to 14400
completed 14300 to 14400


starting 14400 to 14500
completed 14400 to 14500


starting 14500 to 14600
completed 14500 to 14600

In [ ]:

df_tropes.columns  = df_tropes.columns.str.strip()
## see most recent printout to know where to start 
chunk_size = 100
for start in range(10000, len(df_tropes), chunk_size):
    end = start + chunk_size
    print(f"starting {start} to {end}")
    chunk = df_tropes.iloc[start:end].copy()

    # Apply the search_movie function to the chunk
    chunk['imdb_'] = chunk.apply(
        lambda row: search_movie(imdb_link, row['Movie_strip'], row['year']),
        axis=1
    )
    
    # Save the chunk to a CSV or append to an existing one
    chunk.to_csv(f'{root}/Data/tropes_with_imfb.csv', mode='a', header=not pd.io.common.file_exists('results.csv'), index=False)
    print(f"completed {start} to {end} \n\n")

In [129]:
# df_tropes[["Movie", "year"]].compare(
df_merged[["Movie", "year"]]

            Movie  year
0            roma  1972
1           venom  2018
2           bliss  2021
3      witchboard   NaN
4         orlando   NaN
..            ...   ...
599      silenced   NaN
600       armored   NaN
601     mannequin   NaN
602  intermission   NaN
603       berserk  1967

[604 rows x 2 columns]

,Movie,Tropes,Movie_strip,year,ImdbId,_id,poster_url,certificate,runtime,genre,ratingValue,summary_text,ratingCount,director,cast
0,Roma,"AnachronicOrder,AsideGlance,AutoErotica,Blood...",Roma,1972,tt0069191,tt0069191,https://m.media-amazon.com/images/M/MV5BZTk5Zj...,R,120 min,"['Comedy', ' Drama']",7.4,"A fluid, unconnected and sometimes chaotic pro...","11,885","{'name': 'Federico Fellini', 'name_id': 'nm000...","[{'name': 'Britta Barnes', 'name_id': 'nm00555..."
1,Venom,"ADHD,AbledInTheAdaptation,AbortedArc,Acclaime...",Venom,2018,tt1270797,tt1270797,https://m.media-amazon.com/images/M/MV5BNzAwNz...,PG-13,112 min,"['Action', ' Adventure', ' Sci-Fi']",6.7,A failed reporter is bonded to an alien entity...,"371,819","{'name': 'Ruben Fleischer', 'name_id': 'nm0281...","[{'name': 'Tom Hardy', 'name_id': 'nm0362766'}..."
2,Bliss,"AmbiguousDisorder,ChangelingFantasy,Deconstru...",Bliss,2021,tt10333426,tt10333426,https://m.media-amazon.com/images/M/MV5BYmFjNW...,R,103 min,"['Drama', ' Romance', ' Sci-Fi']",5.3,"A mind-bending love story following Greg who, ...","12,342","{'name': 'Mike Cahill', 'name_id': 'nm2648685'}","[{'name': 'Owen Wilson', 'name_id': 'nm0005562..."
3,Witchboard,"AnAxeToGrind,ArchEnemy,ArtisticLicenseHistory...",Witchboard,NaN,tt2256055,tt2256055,https://m.media-amazon.com/images/M/MV5BMTc5Nz...,NaN,NaN,"['Horror', ' Mystery', ' Thriller']",NaN,A re-imagining of the 1986 Horror Classic,NaN,"{'name': 'Chuck Russell', 'name_id': 'nm0751080'}","[{'name': 'Sofia Milos', 'name_id': 'nm0590499'}]"
4,Orlando,"AsideGlance,Bifauxnen,BittersweetEnding,Break...",Orlando,NaN,tt4686656,tt4686656,https://m.media-amazon.com/images/S/sash/NapCx...,NaN,NaN,['Sci-Fi'],NaN,"Lost in the depths of their memory, Niels' and...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546,Silenced,"AdultFear,AngerBornOfWorry,AssholeVictim,BigE...",Silenced,NaN,tt13206338,tt13206338,https://m.media-amazon.com/images/M/MV5BY2M0ZW...,NaN,NaN,['Drama'],NaN,Two female intelligence officers risk everythi...,NaN,NaN,NaN
547,Armored,"BestFriendsInLaw,BigBad,BrokenPedestal,ChaseS...",Armored,NaN,tt13857278,tt13857278,https://m.media-amazon.com/images/S/sash/NapCx...,NaN,NaN,"['Action', ' Thriller']",NaN,Add a Plot,NaN,NaN,NaN
548,Mannequin,"AbhorrentAdmirer,ActorAllusion,AmbiguouslyGay...",Mannequin,NaN,tt12427228,tt12427228,https://m.media-amazon.com/images/M/MV5BNWEzNm...,NaN,NaN,['Horror'],NaN,When Alison takes a job at a new vintage cloth...,NaN,"{'name': 'Louise E. Lathey', 'name_id': 'nm108...","[{'name': 'Joanna Gaskell', 'name_id': 'nm3667..."
549,Intermission,"ArsonMurderAndJaywalking,AttentionWhore,BadBo...",Intermission,NaN,tt5565680,tt5565680,https://m.media-amazon.com/images/S/sash/NapCx...,NaN,NaN,['Comedy'],NaN,"An ambitious young man, down on his luck after...",NaN,"{'name': 'Dartel McRae', 'name_id': 'nm2869419'}","[{'name': 'E.J. Bonilla', 'name_id': 'nm212590..."
550,Berserk,"AlphaBitch,BerserkButton,BloodlessCarnage,Bra...",Berserk,1967,tt0061398,tt0061398,https://m.media-amazon.com/images/M/MV5BM2Q3MD...,Approved,96 min,"['Horror', ' Mystery', ' Thriller']",5.3,A scheming circus owner finds her authority ch...,"1,948","{'name': ""Jim O'Connolly"", 'name_id': 'nm06402...","[{'name': 'Joan Crawford', 'name_id': 'nm00010..."